<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en-US">
<!--<![endif]-->
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width">
<title>Edumonks | Enabling Education</title>
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="http://edumonks.com/xmlrpc.php">
<link rel="alternate" type="application/rss+xml"
	title="Edumonks &raquo; Feed" href="http://edumonks.com/feed/" />
<link rel="alternate" type="application/rss+xml"
	title="Edumonks &raquo; Comments Feed"
	href="http://edumonks.com/comments/feed/" />
<link rel='stylesheet' id='premiumstyle-style-css'
	href='<?php echo $this->config->item('base_url');?>/css/style.css'
	type='text/css' media='all' />
<!--[if lt IE 9]>
<link rel='stylesheet' id='premiumstyle-ie-css'  href='<?php echo $this->config->item('base_url');?>/css/ie.css' type='text/css' media='all' />
<![endif]-->
<script type='text/javascript'
	src='<?php echo $this->config->item('base_url');?>/js/html5.js'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD"
	href="http://edumonks.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml"
	href="http://edumonks.com/wp-includes/wlwmanifest.xml" />

<meta name="generator" content="WordPress 3.8.1" />
<link rel='canonical' href='http://edumonks.com/' />
<link rel='shortlink' href='http://edumonks.com/?p=28' />
<style type="text/css" id="premiumstyle-header-css">
.site-header h1 a,.site-header h2 {
	color: #0a0a0a;
}
</style>
<style type="text/css" id="custom-background-css">
body.custom-background {
	background-color: #e0e0e0;
}
</style>
</head>

<body
	class="home page page-id-28 page-template page-template-home-page-php custom-background">
	<!-- start website header -->
	<?php if(isset($header) && is_array($header)) {
		foreach($header as $key => $_header) {
			print_r($_header);
		}
	} ?>

	<!-- end website header -->
	<!-- start website menu -->
	<?php if(isset($tabMenu) && is_array($tabMenu)) {
		foreach($tabMenu as $key => $_tabMenu) {
			print_r($_tabMenu);
		}
	} ?>
	<!-- end website menu -->
	<div class="wrap fullwidth">
	<?php if(isset($main) && is_array($main)) {
		foreach($main as $key => $_main) {
			print_r($_main);
		}
	} ?>
	</div>
	<?php if(isset($footer) && is_array($footer)) {
		foreach($footer as $key => $_footer) {
			print_r($_footer);
		}
	} ?>
</body>
</html>
<!-- Dynamic page generated in 0.982 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2014-04-04 06:44:49 -->

<!-- Compression = gzip -->
